CREATE TABLE IF NOT EXISTS "Countries" ("_id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" TEXT NOT NULL, "locale" TEXT NOT NULL, "code" INTEGER NOT NULL, "prefixes" TEXT);
CREATE TABLE IF NOT EXISTS "Backup" ("_id" INTEGER PRIMARY KEY, "name" TEXT NOT NULL, "before" TEXT, "after" TEXT, "ROW_ID" INTEGER);

INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Afghanistan', 'AF', '93', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Albania', 'AL', '355', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Algeria', 'DZ', '213', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('American Samoa', 'AS', '1684', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Andorra', 'AD', '376', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Angola', 'AO', '244', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Anguilla', 'AI', '1264', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Antigua And Barbuda', 'AG', '1268', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Argentina', 'AR', '54', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Armenia', 'AM', '374', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Aruba', 'AW', '297', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Australia', 'AU', '61', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Austria', 'AT', '43', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Azerbaijan', 'AZ', '994', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bahamas', 'BS', '1242', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bahrain', 'BH', '973', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bangladesh', 'BD', '880', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Barbados', 'BB', '1246', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Belarus', 'BY', '375', '8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Belgium', 'BE', '32', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Belize', 'BZ', '501', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Benin', 'BJ', '229', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bermuda', 'BM', '1441', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bhutan', 'BT', '975', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bolivia', 'BO', '591', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bosnia And Herzegovina', 'BA', '387', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Botswana', 'BW', '267', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Brazil', 'BR', '55', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('British Virgin Islands', 'VG', '1284', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Brunei', 'BN', '673', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Bulgaria', 'BG', '359', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Burkina Faso', 'BF', '226', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Burundi', 'BI', '257', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cambodia', 'KH', '855', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cameroon', 'CM', '237', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Canada', 'CA', '1', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cape Verde', 'CV', '238', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cayman Islands', 'KY', '1345', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Central African Republic', 'CF', '236', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Chad', 'TD', '235', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Chile', 'CL', '56', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('China', 'CN', '86', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Christmas Island', 'CX', '61', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cocos (Keeling) Islands', 'CC', '61', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Colombia', 'CO', '57', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Comoros', 'KM', '269', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Congo (Republic)', 'CG', '242', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Congo (Democratic)', 'CD', '243', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cook Islands', 'CK', '682', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Costa Rica', 'CR', '506', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ("Cote D' Ivoire", 'CI', '225', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Croatia', 'HR', '385', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cuba', 'CU', '53', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Cyprus', 'CY', '357', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Czech Republic', 'CZ', '420', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Denmark', 'DK', '45', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Djibouti', 'DJ', '253', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Dominica', 'DM', '1767', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Dominican Republic', 'DO', '1809', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Ecuador', 'EC', '593', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Egypt', 'EG', '20', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('El Salvador', 'SV', '503', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Equatorial Guinea', 'GQ', '240', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Eritrea', 'ER', '291', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Estonia', 'EE', '372', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Ethiopia', 'ET', '251', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Falkland Islands', 'FK', '500', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Faroe Islands', 'FO', '298', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Fiji', 'FJ', '679', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Finland', 'FI', '358', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('France', 'FR', '33', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('French Polynesia', 'PF', '689', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Gabon', 'GA', '241', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Gambia', 'GM', '220', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Georgia', 'GE', '995', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Germany', 'DE', '49', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Ghana', 'GH', '233', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Gibraltar', 'GI', '350', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Greece', 'GR', '30', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Greenland', 'GL', '299', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Grenada', 'GD', '1473', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Guam', 'GU', '1671', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Guatemala', 'GT', '502', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Guinea', 'GN', '224', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Guinea-bissau', 'GW', '245', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Guyana', 'GY', '592', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Haiti', 'HT', '509', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Honduras', 'HN', '504', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Hong Kong', 'HK', '852', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Hungary', 'HU', '36', '06');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Iceland', 'IS', '354', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('India', 'IN', '91', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Indonesia', 'ID', '62', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Iran', 'IR', '98', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Iraq', 'IQ', '964', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Ireland', 'IE', '353', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Isle Of Man', 'IM', '44', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Israel', 'IL', '972', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Italy', 'IT', '39', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Jamaica', 'JM', '1876', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Japan', 'JP', '81', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Jordan', 'JO', '962', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Kazakstan', 'KZ', '7', '8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Kenya', 'KE', '254', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Kiribati', 'KI', '686', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Kosovo', 'XK', '381', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Kuwait', 'KW', '965', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Kyrgyzstan', 'KG', '996', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Lao', 'LA', '856', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Latvia', 'LV', '371', '8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Lebanon', 'LB', '961', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Lesotho', 'LS', '266', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Liberia', 'LR', '231', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Libyan', 'LY', '218', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Liechtenstein', 'LI', '423', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Lithuania', 'LT', '370', '0:8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Luxembourg', 'LU', '352', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Macau', 'MO', '853', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Macedonia', 'MK', '389', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Madagascar', 'MG', '261', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Malawi', 'MW', '265', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Malaysia', 'MY', '60', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Maldives', 'MV', '960', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Mali', 'ML', '223', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Malta', 'MT', '356', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Marshall Islands', 'MH', '692', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Mauritania', 'MR', '222', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Mauritius', 'MU', '230', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Mayotte', 'YT', '262', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Mexico', 'MX', '52', '01');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Micronesia', 'FM', '691', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Moldova', 'MD', '373', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Monaco', 'MC', '377', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Mongolia', 'MN', '976', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Montenegro', 'ME', '382', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Montserrat', 'MS', '1664', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Morocco', 'MA', '212', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Mozambique', 'MZ', '258', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Myanmar', 'MM', '95', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Namibia', 'NA', '264', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Nauru', 'NR', '674', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Nepal', 'NP', '977', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Netherlands', 'NL', '31', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Netherlands Antilles', 'AN', '599', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('New Caledonia', 'NC', '687', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('New Zealand', 'NZ', '64', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Nicaragua', 'NI', '505', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Niger', 'NE', '227', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Nigeria', 'NG', '234', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Niue', 'NU', '683', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('North Korea', 'KP', '850', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Northern Mariana Islands', 'MP', '1670', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Norway', 'NO', '47', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Oman', 'OM', '968', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Pakistan', 'PK', '92', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Palau', 'PW', '680', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Panama', 'PA', '507', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Papua New Guinea', 'PG', '675', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Paraguay', 'PY', '595', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Peru', 'PE', '51', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Philippines', 'PH', '63', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Pitcairn', 'PN', '870', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Poland', 'PL', '48', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Portugal', 'PT', '351', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Puerto Rico', 'PR', '1', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Qatar', 'QA', '974', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Romania', 'RO', '40', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Russia', 'RU', '7', '8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Rwanda', 'RW', '250', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saint Barthelemy', 'BL', '590', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saint Helena', 'SH', '290', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saint Kitts And Nevis', 'KN', '1869', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saint Lucia', 'LC', '1758', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saint Martin', 'MF', '1599', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saint Pierre And Miquelon', 'PM', '508', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saint Vincent And The Grenadines', 'VC', '1784', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Samoa', 'WS', '685', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('San Marino', 'SM', '378', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Sao Tome And Principe', 'ST', '239', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Saudi Arabia', 'SA', '966', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Senegal', 'SN', '221', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Serbia', 'RS', '381', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Seychelles', 'SC', '248', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Sierra Leone', 'SL', '232', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Singapore', 'SG', '65', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Slovakia', 'SK', '421', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Slovenia', 'SI', '386', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Solomon Islands', 'SB', '677', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Somalia', 'SO', '252', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('South Africa', 'ZA', '27', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('South Korea', 'KR', '82', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Spain', 'ES', '34', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Sri Lanka', 'LK', '94', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Sudan', 'SD', '249', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Suriname', 'SR', '597', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Swaziland', 'SZ', '268', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Sweden', 'SE', '46', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Switzerland', 'CH', '41', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Syria', 'SY', '963', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Taiwan', 'TW', '886', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Tajikistan', 'TJ', '992', '8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Tanzania', 'TZ', '255', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Thailand', 'TH', '66', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Timor-leste', 'TL', '670', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Togo', 'TG', '228', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Tokelau', 'TK', '690', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Tonga', 'TO', '676', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Trinidad And Tobago', 'TT', '1868', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Tunisia', 'TN', '216', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Turkey', 'TR', '90', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Turkmenistan', 'TM', '993', '8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Turks And Caicos Islands', 'TC', '1649', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Tuvalu', 'TV', '688', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Uganda', 'UG', '256', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Ukraine', 'UA', '380', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('United Arab Emirates', 'AE', '971', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('United Kingdom', 'GB', '44', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('United States', 'US', '1', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('US. Virgin Islands', 'VI', '1340', '1');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Uruguay', 'UY', '598', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Uzbekistan', 'UZ', '998', '8');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Vanuatu', 'VU', '678', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Venezuela', 'VE', '58', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Vietnam', 'VN', '84', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Wallis And Futuna', 'WF', '681', '');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Yemen', 'YE', '967', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Zambia', 'ZM', '260', '0');
INSERT INTO `Countries` (`name`, `locale`, `code`, `prefixes`) VALUES ('Zimbabwe', 'ZW', '263', '0');